# Docker Composeファイルのバージョンを指定
version: "3.9"
services:
  # サービス名：サービス名に app (アプリケーションサーバー)の名前を付けて定義
  app:
    # ビルドコンテキストを指定
    # ビルドコンテキスト(build context)：docker buildを実行する際の現在の作業ディレクトリのこと
    build: ./infra/php
    # ホスト側の ./src ディレクトリをappサービスのコンテナ内 /data へマウント
    volumes:
      - ./src:/data
  web:
    # コンテナを起動させるイメージを指定
    # nginxは1.10, 1.12 等の偶数のバージョンが安定バージョン
    image: nginx:1.20-alpine
    # nginxへ外(ホスト側)からコンテナ内へアクセスさせるため公開用のポートを設定
    # ホスト側:コンテナ側 と設定
    ports:
      - 8080:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data